name: Automated API tests using Postman CLI

on:
  push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Generate Maven Wrapper
        run: |
          mkdir -p .mvn/wrapper
          curl -o .mvn/wrapper/maven-wrapper.jar -L https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.7.7/maven-wrapper-0.7.7.jar
          curl -o .mvn/wrapper/maven-wrapper.properties -L https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.7.7/maven-wrapper-0.7.7.pom
          echo "distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.4/apache-maven-3.8.4-bin.zip" > .mvn/wrapper/maven-wrapper.properties
          chmod +x .mvn/wrapper/maven-wrapper.jar

      - name: Build with Maven
        run: |
          chmod +x .mvn/wrapper/maven-wrapper.jar
          ./.mvn/wrapper/maven-wrapper.jar clean install

      - name: Run Spring Boot Application
        run: |
          chmod +x .mvn/wrapper/maven-wrapper.jar
          ./.mvn/wrapper/maven-wrapper.jar spring-boot:run

      - name: Run API tests
        run: |
          postman collection run "21534077-e55ed6dd-a433-4d27-a88d-1b739abcdb1b" -e "21534077-7b74c5b6-fe4f-4ddf-b224-07a161c0ef22"
