name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'  # You can adjust the Java version as needed

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: demo-artifact
          path: E:\Level_4\ITQA\Assignment\IS3440_GroupAssignment

      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: demo-artifact
          path: E:\Level_4\ITQA\Assignment\IS3440_GroupAssignment

      - name: Run API tests
        run: |
          cd E:\Level_4\ITQA\Assignment\IS3440_GroupAssignment
          java -jar demo-0.0.1-SNAPSHOT.jar

      - name: Run Postman API tests
        run: |
          postman collection run "21534077-e55ed6dd-a433-4d27-a88d-1b739abcdb1b" -e "21534077-7b74c5b6-fe4f-4ddf-b224-07a161c0ef22"
