name: Automated API tests using Postman CLI

on:
  push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run JAR file
        run: java -jar demo-0.0.1-SNAPSHOT.jar

      - name: Run API tests
        run: |
          postman collection run "21534077-e55ed6dd-a433-4d27-a88d-1b739abcdb1b" -e "21534077-7b74c5b6-fe4f-4ddf-b224-07a161c0ef22"
