name: Automated API tests using Postman CLI

on:
  push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Generate Maven archetype
        run: |
          mvn archetype:generate -DgroupId=com.example.demo -DartifactId=application -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

      - name: Generate Maven Wrapper Script
        run: |
          mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.8.4

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Run Spring Boot Application
        run: |
          chmod +x mvnw
          ./mvnw spring-boot:run

      - name: Run API tests
        run: |
          postman collection run "21534077-e55ed6dd-a433-4d27-a88d-1b739abcdb1b" -e "21534077-7b74c5b6-fe4f-4ddf-b224-07a161c0ef22"
